name: Change content in file into another

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: |
          cat tag_html.md
          sed -i -e 's/godot-admob-android/godot-admob-ios/g' tag_html.md
          cat tag_html.md
        working-directory: change_content
